import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
	return (
		<div>
			<Link>Ez 
Home
Menu
About us
Search here everything...
Super voucher            in now
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Imperdiet diam sit magna pellentesque sed consectetur. Velit diam velit augue.
Explore Now
Popular
Food
Drink
Vegetable
Fruit
-20%
New
-15%
Hot
Hash browns
Cremini mushrooms
White Bread
Condensed milk
Sold: 610
Sold: 610
Sold: 610
Sold: 610
5 USD
210 USD
3 USD
50 USD
-20%
New
-15%
Hot
Romaine lettuce
Venison
Rice vinegar
Margarine
Sold: 610
Sold: 610
Sold: 610
Sold: 610
5 USD
210 USD
3 USD
50 USD
Show more
Merry christmas
Happy 
     new year
High Quality
Warrany Protection
24 / 7 Support
crafted from top materials
Over 2 years
Dedicated support
Back to top
EzOrder.
Menu
Account
Stay Connected
Stay Updated
Worldwide furniture store since 2020. We sell over 1000+ branded products on our website
Products
My Account
Facebook
Enter your email
Rooms
Checkout
Instagram
Sawojajar Malang, Vietnam
Inspirations
My Cart
Twitter
+6289 456 3455
About Us
My catalog
www.ezorder.com
Terms & Policy</Link>x
		</div>
		// <div className={styles.container}>
		// 	<Head>
		// 		<title>Create Next App</title>
		// 		<meta name="description" content="Generated by create next app" />
		// 		<link rel="icon" href="/favicon.ico" />
		// 	</Head>

		// 	<main className={styles.main}>
		// 		<h1 className={styles.title}>
		// 			Welcome to <a href="https://nextjs.org">Next.js!</a>
		// 		</h1>

		// 		<p className={styles.description}>
		// 			Get started by editing{' '}
		// 			<code className={styles.code}>pages/index.js</code>
		// 		</p>

		// 		<div className={styles.grid}>
		// 			<a href="https://nextjs.org/docs" className={styles.card}>
		// 				<h2>Documentation &rarr;</h2>
		// 				<p>Find in-depth information about Next.js features and API.</p>
		// 			</a>

		// 			<a href="https://nextjs.org/learn" className={styles.card}>
		// 				<h2>Learn &rarr;</h2>
		// 				<p>Learn about Next.js in an interactive course with quizzes!</p>
		// 			</a>

		// 			<a
		// 				href="https://github.com/vercel/next.js/tree/master/examples"
		// 				className={styles.card}
		// 			>
		// 				<h2>Examples &rarr;</h2>
		// 				<p>Discover and deploy boilerplate example Next.js projects.</p>
		// 			</a>

		// 			<a
		// 				href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
		// 				className={styles.card}
		// 			>
		// 				<h2>Deploy &rarr;</h2>
		// 				<p>
		// 					Instantly deploy your Next.js site to a public URL with Vercel.
		// 				</p>
		// 			</a>
		// 		</div>
		// 	</main>

		// 	<footer className={styles.footer}>
		// 		<a
		// 			href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
		// 			target="_blank"
		// 			rel="noopener noreferrer"
		// 		>
		// 			Powered by{' '}
		// 			<span className={styles.logo}>
		// 				<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
		// 			</span>
		// 		</a>
		// 	</footer>
		// </div>
	);
}
